#######################################
# Mariadb and Neo4j databases with Adminer and Neo4j browser for views.
#
# Adminer: Navigate to localhost:8080, set server as mariadb, user as root, and password as example
#
# Neo4j: Navigate to localhost:7474
#######################################
version: '3.1'

services:

  mariadb:
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ./output:/output
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: movies

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  neo4j:
    image: neo4j
    restart: always
    environment:
      NEO4J_AUTH: none
    ports:
      - 7474:7474
      - 7687:7687
